import {
  defaultCrtSettings,
  type CrtPreset,
  type CrtSettings,
  normalizeCrtSettings,
} from '../types/crt';

const CUSTOM_PRESETS_KEY = 'crtify.customPresets.v1';

export const BUILTIN_PRESETS: CrtPreset[] = [
  {
    id: 'default',
    name: 'Studio Default',
    description: 'A balanced, warm CRT starting point with moderate curvature and scanlines.',
    builtin: true,
    settings: { ...defaultCrtSettings },
  },
  {
    id: 'vhs-tape',
    name: 'VHS Tape',
    description: 'Noisy home-video playback with color separation, flicker, interlace, and roll.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.22,
      scanlineIntensity: 0.55,
      scanlineCount: 420,
      aberration: 0.008,
      vignette: 0.7,
      noise: 0.14,
      bloom: 0.15,
      tint: '#ffb070',
      tintStrength: 0.22,
      brightness: 0.95,
      contrast: 1.2,
      flicker: true,
      flickerIntensity: 0.06,
      rgbMask: 0.35,
      interlace: 0.45,
      rollBar: 0.25,
      phosphorDecay: 0.15,
      showBezel: true,
    },
  },
  {
    id: 'arcade',
    name: 'Arcade Cabinet',
    description: 'Punchy arcade phosphors with strong scanlines, RGB mask, glow, and curved glass.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.45,
      scanlineIntensity: 0.65,
      scanlineCount: 260,
      aberration: 0.004,
      vignette: 0.55,
      noise: 0.04,
      bloom: 0.45,
      tint: '#7dff9a',
      tintStrength: 0.28,
      brightness: 1.1,
      contrast: 1.25,
      rgbMask: 0.55,
      interlace: 0.2,
      rollBar: 0,
      phosphorDecay: 0.35,
      showBezel: true,
    },
  },
  {
    id: 'amber-terminal',
    name: 'Amber Terminal',
    description: 'Warm monochrome terminal glow with phosphor persistence and CRT-affected overlays.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.18,
      scanlineIntensity: 0.5,
      scanlineCount: 320,
      aberration: 0.001,
      vignette: 0.4,
      noise: 0.03,
      bloom: 0.35,
      tint: '#ffb000',
      tintStrength: 0.55,
      brightness: 1.05,
      contrast: 1.15,
      rgbMask: 0.15,
      interlace: 0.1,
      phosphorDecay: 0.45,
      showBezel: false,
    },
    crtAffectText: true,
  },
  {
    id: 'broadcast',
    name: 'Broadcast News',
    description: 'Clean studio video with fine scanlines, restrained color drift, and a TV bezel.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.12,
      scanlineIntensity: 0.25,
      scanlineCount: 480,
      aberration: 0.002,
      vignette: 0.35,
      noise: 0.02,
      bloom: 0.12,
      tint: '#dce8ff',
      tintStrength: 0.08,
      brightness: 1.05,
      contrast: 1.08,
      rgbMask: 0.2,
      interlace: 0.55,
      rollBar: 0.05,
      phosphorDecay: 0.05,
      showBezel: true,
    },
  },
  {
    id: 'security-cam',
    name: 'Security Cam',
    description: 'High-contrast surveillance feed with grain, heavy vignette, interlace, and sync roll.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.08,
      scanlineIntensity: 0.35,
      scanlineCount: 360,
      aberration: 0.0015,
      vignette: 0.8,
      noise: 0.18,
      bloom: 0.05,
      tint: '#c0c8b0',
      tintStrength: 0.35,
      brightness: 0.9,
      contrast: 1.35,
      flicker: true,
      flickerIntensity: 0.04,
      rgbMask: 0.1,
      interlace: 0.7,
      rollBar: 0.4,
      phosphorDecay: 0.1,
      showBezel: false,
    },
  },
  {
    id: 'green-phosphor',
    name: 'Green Phosphor',
    description: 'Classic P1 green monochrome terminal with long phosphor trails and CRT-affected overlays.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.16,
      scanlineIntensity: 0.55,
      scanlineCount: 300,
      aberration: 0.0008,
      vignette: 0.45,
      noise: 0.04,
      bloom: 0.4,
      tint: '#33ff66',
      tintStrength: 0.62,
      brightness: 1.05,
      contrast: 1.2,
      rgbMask: 0.12,
      interlace: 0.15,
      rollBar: 0,
      phosphorDecay: 0.55,
      showBezel: false,
    },
    crtAffectText: true,
  },
  {
    id: 'cold-tube',
    name: 'Cold Tube',
    description: 'Near-monochrome living-room CRT: cool gray phosphors, hard contrast, and strong interlace.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.28,
      scanlineIntensity: 0.5,
      scanlineCount: 380,
      aberration: 0.001,
      vignette: 0.55,
      noise: 0.06,
      bloom: 0.18,
      tint: '#d8dee8',
      tintStrength: 0.12,
      brightness: 0.98,
      contrast: 1.3,
      rgbMask: 0.28,
      interlace: 0.65,
      rollBar: 0.08,
      phosphorDecay: 0.12,
      showBezel: true,
    },
  },
  {
    id: 'haunted-crt',
    name: 'Haunted CRT',
    description: 'Broken late-night set: heavy noise, flicker, sync roll, and sickly green-violet drift.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.38,
      scanlineIntensity: 0.7,
      scanlineCount: 240,
      aberration: 0.014,
      vignette: 0.85,
      noise: 0.28,
      bloom: 0.22,
      tint: '#b8ff9a',
      tintStrength: 0.32,
      brightness: 0.85,
      contrast: 1.4,
      flicker: true,
      flickerIntensity: 0.12,
      rgbMask: 0.4,
      interlace: 0.55,
      rollBar: 0.55,
      phosphorDecay: 0.4,
      showBezel: true,
    },
  },
  {
    id: 'trinitron',
    name: 'Trinitron',
    description: 'Soft living-room Trinitron: mild curve, cool-white bloom, aperture grille, and a chrome bezel.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.18,
      scanlineIntensity: 0.3,
      scanlineCount: 440,
      aberration: 0.0025,
      vignette: 0.4,
      noise: 0.025,
      bloom: 0.28,
      tint: '#e8f0ff',
      tintStrength: 0.1,
      brightness: 1.08,
      contrast: 1.05,
      rgbMask: 0.45,
      interlace: 0.35,
      rollBar: 0,
      phosphorDecay: 0.08,
      showBezel: true,
    },
  },
  {
    id: 'neon-cyber',
    name: 'Neon Cyber',
    description: 'Magenta-cyan night city CRT with thick bloom, RGB mask, and punchy contrast.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.32,
      scanlineIntensity: 0.45,
      scanlineCount: 280,
      aberration: 0.01,
      vignette: 0.6,
      noise: 0.05,
      bloom: 0.55,
      tint: '#ff3dc8',
      tintStrength: 0.28,
      brightness: 1.12,
      contrast: 1.28,
      rgbMask: 0.6,
      interlace: 0.25,
      rollBar: 0.05,
      phosphorDecay: 0.3,
      showBezel: false,
    },
  },
  {
    id: 'night-vision',
    name: 'Night Vision',
    description: 'IR-cam green wash with crushed blacks, grain, heavy vignette, and almost no bloom.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.06,
      scanlineIntensity: 0.28,
      scanlineCount: 340,
      aberration: 0.0005,
      vignette: 0.9,
      noise: 0.22,
      bloom: 0.02,
      tint: '#4dff6a',
      tintStrength: 0.7,
      brightness: 0.88,
      contrast: 1.45,
      flicker: true,
      flickerIntensity: 0.03,
      rgbMask: 0.05,
      interlace: 0.4,
      rollBar: 0.15,
      phosphorDecay: 0.05,
      showBezel: false,
    },
  },
  {
    id: 'soft-lofi',
    name: 'Soft Lo-Fi',
    description: 'Washed pastel tape look: low contrast, gentle noise, soft bloom, and little mask texture.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.2,
      scanlineIntensity: 0.22,
      scanlineCount: 360,
      aberration: 0.004,
      vignette: 0.35,
      noise: 0.08,
      bloom: 0.3,
      tint: '#ffc8a8',
      tintStrength: 0.18,
      brightness: 1.1,
      contrast: 0.92,
      rgbMask: 0.08,
      interlace: 0.15,
      rollBar: 0.1,
      phosphorDecay: 0.18,
      showBezel: false,
    },
  },
  {
    id: 'fishbowl',
    name: 'Fishbowl CRT',
    description: 'Deep barrel glass with strong vignette and aperture grille — the whole image sits inside the tube.',
    builtin: true,
    settings: {
      ...defaultCrtSettings,
      curvature: 0.72,
      scanlineIntensity: 0.55,
      scanlineCount: 260,
      aberration: 0.006,
      vignette: 0.75,
      noise: 0.05,
      bloom: 0.25,
      tint: '#ffb070',
      tintStrength: 0.16,
      brightness: 1.0,
      contrast: 1.15,
      rgbMask: 0.5,
      interlace: 0.3,
      rollBar: 0.05,
      phosphorDecay: 0.2,
      showBezel: true,
    },
  },
];

function readCustomPresets(): CrtPreset[] {
  try {
    const raw = localStorage.getItem(CUSTOM_PRESETS_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as CrtPreset[];
    if (!Array.isArray(parsed)) return [];
    return parsed.map((preset) => ({
      ...preset,
      builtin: false,
      settings: normalizeCrtSettings(preset.settings),
    }));
  } catch {
    return [];
  }
}

function writeCustomPresets(presets: CrtPreset[]) {
  localStorage.setItem(CUSTOM_PRESETS_KEY, JSON.stringify(presets));
}

export function listPresets(): CrtPreset[] {
  return [...BUILTIN_PRESETS, ...readCustomPresets()];
}

export function saveCustomPreset(name: string, settings: CrtSettings, crtAffectText?: boolean): CrtPreset {
  const preset: CrtPreset = {
    id: `custom-${crypto.randomUUID()}`,
    name: name.trim() || 'Custom Look',
    description: 'A custom look saved from your current CRT effect settings.',
    builtin: false,
    settings: normalizeCrtSettings(settings),
    crtAffectText,
  };
  const next = [...readCustomPresets(), preset];
  writeCustomPresets(next);
  return preset;
}

export function deleteCustomPreset(id: string) {
  writeCustomPresets(readCustomPresets().filter((preset) => preset.id !== id));
}

export function findPreset(id: string): CrtPreset | undefined {
  return listPresets().find((preset) => preset.id === id);
}
